### ISSUE TITLE
Nahrazení LogicException u metody run().

### ISSUE THREAD

**Issue by mrtnzlml** [besanek/PresenterTester#2]
Pokud někdo spouští:

``` php
$response = $tester->run();
```

Následně provede testy a chce vytvořit novou response, bylo by užitečné, aby nebylo třeba spouštět clean:

``` php
$tester->clean();
$response = $tester->run();
```

V současné době je to nutná prerekvizita ke spuštění, takže místo výjimky by se to dalo zautomatizovat. Opět bych tu metodu však zachoval public...

**Comment by besanek** [comment]
Už vím v čem je zakopán pes a proč jsem tu clean nedal přímo na tvrdo do run. Jde o to, že metoda getPresenterComponent() dovoluje vytvořit a získat presenter před run() a libovolně upravit. Např. mu nacpat mocky modelů. Pokud by se clean volal napevno, tak by tento upravený presenter smazal. 

Ale vím jak tohle vyřešit.

Další problém je u opět vyjímek. Jelikož se vyhazují pokaždé, když se někdo pokusí nastavit něco, k čemu už existuje vytvořený presenter / request. 

Mám určitou vizi, jak tohle všechno vyřešit, ale bude to na více úprav.

**Comment by besanek** [comment]
Tak jsem tuto funkcionalitu přidal do experimentální větve. 8694445a01124aff66533331d970e8d53371c8ac

Pokud jsou nějaké výhrady k implementaci nebo použití, tak momentálně je ten pravý čas. Postupně dodám nějaké testy a pokud s tím nebudou žádné problémy, tak zařadím do masteru.

**Comment by besanek** [comment]
Použil jsi někde ten `autoclean`? Po několika projektech jsem zjistil, že jsem prakticky `autoclean` či samotnou metodu `clean()` téměř vůbec nepoužil, jelikož v každém testu vytvářím jeden presenter. Pokud není žádná rozumná use case, tak bych tu větev a tuto issue prohlásil za uzavřenou.

**Comment by mrtnzlml** [comment]
Můžeme to použít za uzavřené. Vytvořil jsem si vlastní primitivní testovací třídu https://github.com/mrtnzlml/www.zeminem.cz/blob/master/tests/Presenter.php, díky které můžu testovat dostatečně pohodlně viz https://github.com/mrtnzlml/www.zeminem.cz/blob/master/tests/presenters/SinglePresenterTest.phpt. Už mám vymyšleno několik dalších zjednodušení, každopádně koncept asi zůstane.
